export default [
    {
        name:"首页",
        path:"index",
        redirect:'',
    },
    {
        name:"PDF预览",
        path:'PDFviewer',
        redirect:'PDF预览',
    },
    {
        name:"裁剪",
        path:'cropper',
        redirect:'裁剪组件',
    },
    {
        name:"组件",
        path:'content',
        redirect:'组件',
    },
    {
        name:"图片拖动",
        path:'modelSet',
        redirect:'图片拖动',
    },
]
