export default [
    {
        name:"首页",
        path:"index",
        redirect:'',
    },
    {
        name:"学习",
        path:'learning',
        redirect:'',
    },
    {
        name:"题库",
        path:'questionBank',
        redirect:'',
    },
    {
        name:"培训管理",
        path:'trainingManagement',
        redirect:'培训管理',
    },
]