export default [
    {
        name:"首页",
        path:"index",
        redirect:'',
    },
    {
        name:"学习资料",
        path:'learningMaterials',
        redirect:'',
    },
    {
        name:"互动问答",
        path:'questionBank',
        redirect:'',
    },
    {
        name:"培训管理",
        path:'trainingManagement',
        redirect:'培训管理',
    },
    {
        name:"沟通",
        path:"communication",
        redirect:'',
    },
    {
        name:"组织架构",
        path:'personnelManagement',
        redirect:'',
    },
]