export default {
    B:[
        {
            name: "白帆",
            num: `123xx33`,
            department:`供电局`,
            job:`科员`,
            level:`警员`,
            lpn:`14546872121`,
            spn:`432345`,
            icon:``,
        },
        {
            name: "包丽",
            num: `123xx33`,
            department:`供电局`,
            job:`科员`,
            level:`警员`,
            lpn:`14546872121`,
            spn:`432345`,
            icon:``,
        },
        {
            name: "白帆",
            num: `123xx33`,
            department:`供电局`,
            job:`科员`,
            level:`警员`,
            lpn:`14546872121`,
            spn:`432345`,
            icon:``,
        },
        {
            name: "包丽",
            num: `123xx33`,
            department:`供电局`,
            job:`科员`,
            level:`警员`,
            lpn:`14546872121`,
            spn:`432345`,
            icon:``,
        },
    ],
    C:[
        {
            name: "蔡亮",
            num: `123xx33`,
            department:`供电局`,
            job:`科员`,
            level:`警员`,
            lpn:`14546872121`,
            spn:`432345`,
            icon:``,
        },
        {
            name: "崔瑟琪",
            num: `123xx33`,
            department:`供电局`,
            job:`科员`,
            level:`警员`,
            lpn:`14546872121`,
            spn:`432345`,
            icon:``,
        },
        {
            name: "蔡亮",
            num: `123xx33`,
            department:`供电局`,
            job:`科员`,
            level:`警员`,
            lpn:`14546872121`,
            spn:`432345`,
            icon:``,
        },
        {
            name: "崔瑟琪",
            num: `123xx33`,
            department:`供电局`,
            job:`科员`,
            level:`警员`,
            lpn:`14546872121`,
            spn:`432345`,
            icon:``,
        },
    ],

    L:[
        {
        name: "刘方",
        num: `123xx33`,
        department:`供电局`,
        job:`科员`,
        level:`警员`,
        lpn:`14546872121`,
        spn:`432345`,
        icon:``,
        },
        {
            name: "刘为",
            num: `123xx33`,
            department:`供电局`,
            job:`科员`,
            level:`警员`,
            lpn:`14546872121`,
            spn:`432345`,
            icon:``,
        },
        {
            name: "廖罚",
            num: `123xx33`,
            department:`供电局`,
            job:`科员`,
            level:`警员`,
            lpn:`14546872121`,
            spn:`432345`,
            icon:``,
        },
        {
            name: "柳玉",
            num: `123xx33`,
            department:`供电局`,
            job:`科员`,
            level:`警员`,
            lpn:`14546872121`,
            spn:`432345`,
            icon:``,
        },
        {
            name: "刘方",
            num: `123xx33`,
            department:`供电局`,
            job:`科员`,
            level:`警员`,
            lpn:`14546872121`,
            spn:`432345`,
            icon:``,
        },
        {
            name: "刘方",
            num: `123xx33`,
            department:`供电局`,
            job:`科员`,
            level:`警员`,
            lpn:`14546872121`,
            spn:`432345`,
            icon:``,
        },
        {
            name: "刘方",
            num: `123xx33`,
            department:`供电局`,
            job:`科员`,
            level:`警员`,
            lpn:`14546872121`,
            spn:`432345`,
            icon:``,
        },
        {
            name: "刘方",
            num: `123xx33`,
            department:`供电局`,
            job:`科员`,
            level:`警员`,
            lpn:`14546872121`,
            spn:`432345`,
            icon:``,
        },
    ],
    X:[
        {
            name: "徐璐",
            num: `123xx33`,
            department:`供电局`,
            job:`科员`,
            level:`警员`,
            lpn:`14546872121`,
            spn:`432345`,
            icon:``,
        },
        {
            name: "徐璐",
            num: `123xx33`,
            department:`供电局`,
            job:`科员`,
            level:`警员`,
            lpn:`14546872121`,
            spn:`432345`,
            icon:``,
        },
        {
            name: "徐璐",
            num: `123xx33`,
            department:`供电局`,
            job:`科员`,
            level:`警员`,
            lpn:`14546872121`,
            spn:`432345`,
            icon:``,
        },
        {
            name: "许然",
            num: `123xx33`,
            department:`供电局`,
            job:`科员`,
            level:`警员`,
            lpn:`14546872121`,
            spn:`432345`,
            icon:``,
        },
    ],


}




